### ISSUE TITLE
pom file problem

### ISSUE THREAD

**Issue by allen-buck** [goxr3plus/Simplest-Spring-Boot-Hello-World#6]
There is a missing </plugin> tag before the </plugins> tag on line 26.  Won't build out of the box.  
I'm using this a simple project in an online tools class.  It's much simpler than the suggested project. 

Thanks

**Comment by goxr3plus** [comment]
Hey can you pull request so i fix :)?

**Comment by goxr3plus** [comment]
Its fixed now :)

**Comment by allen-buck** [comment]
Thanks

Allen Buck | Enterprise Middleware Specialist

[cid:image007.jpg@01D5F2F3.79631910]<https://stateoftennessee.formstack.com/forms/sts_howsmyservice>
